# Generated by Django 3.0.4 on 2020-03-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcamper_api', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamps',
            name='publisher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='devcamper_api.Users'),
        ),
    ]
