# Generated by Django 3.0.4 on 2020-03-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcamper_api', '0003_bootcamps_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamps',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devcamper_api.Users'),
        ),
    ]
