# Generated by Django 3.0.4 on 2020-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcamper_api', '0004_auto_20200319_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('weeks', models.PositiveIntegerField()),
                ('tuition', models.PositiveIntegerField()),
                ('minimumSkill', models.CharField(max_length=15)),
                ('scholarhipsAvailable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bootcamps',
            name='courses',
            field=models.ManyToManyField(to='devcamper_api.Courses'),
        ),
    ]
