# Generated by Django 3.0.4 on 2020-03-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcamper_api', '0005_auto_20200320_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('rating', models.PositiveIntegerField()),
                ('forWhichBootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devcamper_api.Bootcamps')),
            ],
        ),
    ]
