# Generated by Django 3.0.4 on 2020-06-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcamper_api', '0007_auto_20200627_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devcamper_api.User'),
        ),
    ]
